export const homeData = [
  {
    id: 1,
    name: "SE7EN",
    rating: 8.6,
    time: "2hr : 22mins",
    desc: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    starring: "Brad Pitt, Morgan Freeman, Kevin Spacey, Gwyneth Paltrow",
    genres: "Crime, Drama, Mystery",
    tags: "Crime, Drama, Mystery, Thriller",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "20-Jan-1997",
  },
  {
    id: 2,
    name: "THE GODFATHER",
    rating: 9.2,
    time: "2hr : 55mins",
    desc: "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate. ",
    starring: "Al Pacino, Robert De Niro, Robert Duvall",
    genres: "Crime, Drama",
    tags: "Crime, Drama, Family",
    cover: "../images/home2.jpg",
    video: "../video/video2.mp4",
    date: "24-Mar-1972",
  },
  {
    id: 3,
    name: "Goodfellas",
    rating: 8.7,
    time: "2hr : 26mins",
    desc: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate. ",
    starring: "Ray Liotta, Robert De Niro, Joe Pesci",
    genres: "Crime, Drama, Biography",
    tags: "Crime, Drama, Biography ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "19-Sep-1990",
  },
  {
    id: 4,
    name: "THE DEPARTED",
    rating: 8.5,
    time: "1hr : 55mins",
    desc: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    starring: "Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg",
    genres: "Crime, Drama, Thriller",
    tags: "Crime, Drama, Mystery, Thiller",
    cover: "../images/home4.jpg",
    video: "../video/video4.mp4",
    date: "6-Okt-2006",
  },
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "The Dark Knight",
    time: "2hr : 32mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "The Silince of The Lambs",
    time: "1hr : 58mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Joker",
    time: "2hr : 2mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "Interstellar",
    time: "2hr : 49mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Parasite",
    time: "2hr : 12mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/bat.jpg",
    name: "The Batman",
    time: "2hr : 56mins",
  },
  {
    id: 2,
    cover: "../images/upcome/inc.jpg",
    name: "(Inception)",
    time: "2hr : 28mins",
  },
  {
    id: 3,
    cover: "../images/upcome/500.jpg",
    name: "(500) Days of Summer",
    time: "1hr : 28mins",
  },
  {
    id: 4,
    cover: "../images/upcome/leon.jpg",
    name: "Léon: The Professional",
    time: "1hr : 50mins",
  },
  {
    id: 5,
    cover: "../images/upcome/irish.jpg",
    name: "The Irishman",
    time: "3hr : 29mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "INGLORIUS BASTERD",
    rating: 8.3,
    time: "2hr : 33mins",
    desc: "In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same..",
    starring: "Brad Pitt, Cristoph Waltz, Michael Fassbender, Daniel Druhl",
    genres: "Adventure, Drama, War",
    tags: "Action, Adventures, War",
    cover: "../images/img/slide1.png",
    date: "4-Feb-1994",
  },
  {
    id: 2,
    name: "SCHINDLER'S LIST",
    rating: 9.0,
    time: "3hr : 15mins",
    desc: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis. ",
    starring: "Liam Neeson, Ralp Fiennes, Ben Kingsley",
    genres: "Biography, Drama, History",
    tags: "Biography, Drama, History",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "THE PIANIST",
    rating: 8.5,
    time: "2hr : 30mins",
    desc: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II. ",
    starring: "Adrien Brody,Thomas Kretschmann,Frank Finlay, Emilia Fox ",
    genres: "Biography, Drama, Music",
    tags: "Biography, Drama, History, Music ",
    cover: "../images/img/slide3.jpg",
    date: "6-Sep-2002",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "Fight Club",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Django Unchained",
    time: "2hr : 45mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "Goodfellas",
    time: "2hr : 26mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Gone Girl",
    time: "2hr : 29mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "Joker",
    time: "2hr : 2mins",
  },
]
